services:
  - type: web
    name: livestream-dashboard-pro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /healthz
